#!/bin/sh
# cd to this directory
BASEDIR=$(dirname $0)
cd "$BASEDIR"

# check openssl existence
command -v openssl >/dev/null 2>&1 || { echo >&2 "ERROR: openssl not found"; exit 1; }

cat <<EOF > tmpconfig
[ req ]
distinguished_name = req_distinguished_name
prompt = no

[ req_distinguished_name ]
C = SO
ST = Banaadir
L = Mogadishu
O = arrtorrent
CN = arrtorrent
EOF

openssl genrsa -out server.key 4096 || echo 'ERROR: generating private key failed'
openssl req -new -x509 -days 365 -sha256 -key server.key -out server.crt -config tmpconfig || echo 'ERROR: generating certificate failed'
rm tmpconfig

